import localFont from "next/font/local";
import { NextUIProvider } from '@nextui-org/react';
import "./globals.css";
import App from "./components/Navbar/Navbar";
// import MainNav from "./components/Navbar/Navbar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CareerBoost",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextUIProvider>
          <App/>
        {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
